### ISSUE TITLE
Fatal error: failed to unpack FSPS code

### ISSUE THREAD

**Issue by liempi** [galacticusorg/galacticus#342]
Hi all!

I updated recently Galacticus and I get an issue. My parameter file and the error log file is attached. Anyone know what is happening?  Before the update the parameter file worked well.  Many Thanks!

(I attached the parameter file as a log file but changing the extension to xml should work)
 
[error.log](https://github.com/galacticusorg/galacticus/files/10201263/error.log)
[100.C.log](https://github.com/galacticusorg/galacticus/files/10201265/100.C.log)

Thanks again, 
Matias

**Comment by abensonca** [comment]
The error is happening when Galacticus tries to unpack the FSPS code - which is downloaded and built automatically when needed. It looks like the download of FSPS failed previously, leaving an incomplete download.

I'd suggest removing the download like this:
```
rm -rf $GALACTICUS_DATA_PATH/dynamic/FSPS_*.tar.gz
rm -rf $GALACTICUS_DATA_PATH/dynamic/fsps-3.2
```
and trying to run your model again. It should retry downloading FSPS. If it still fails post the error message that you get from this attempt.

**Comment by liempi** [comment]
Now is working. Thanks!
