### ISSUE TITLE
Error while compiling: /usr/bin/ld: cannot find -lz

### ISSUE THREAD

**Issue by grossa4747** [galacticusorg/galacticus#402]
Hi,
I am trying to compile Galacticus, and am getting an error that I don't understand. Here are the details:

I am running Ubuntu 20.04, and have installed gcc 10.1, gsl 2.6, hdf5 1.8.20, fox 4.1.0, and BLAS to the folder /usr/local/galacticus. I have added this folder to the path and library path, and installed the required perl modules via perl -MCPAN -e 'install(Scalar::Util)'
Here is an excerpt from the current environment: 

PATH=/usr/local/galacticus/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
LD_LIBRARY_PATH=/usr/local/galacticus/lib64:

I am initializing the compilation via the following series of commands:

export GALACTICUS_EXEC_PATH=`pwd`
export INSTALL_PATH=/usr/local/galacticus
export GALACTICUS_FCFLAGS="-fintrinsic-modules-path /usr/local/galacticus/finclude -fintrinsic-modules-path /usr/local/galacticus/include -fintrinsic-modules-path /usr/local/galacticus/include/gfortran -fintrinsic-modules-path /usr/local/galacticus/lib/gfortran/modules -L/usr/local/galacticus/lib -L/usr/local/galacticus/lib64"
export GALACTICUS_CFLAGS="-I/usr/local/galacticus/include"
export GALACTICUS_CPPFLAGS="-I/usr/local/galacticus/include"
make -j8 Galacticus.exe

The compilation runs for quite a while, before producing the following error:
...
...
gfortran -c ./work/build/Galacticus.p.F90 -o ./work/build/Galacticus.o -ffree-line-length-none -frecursive -DBUILDPATH=\'./work/build\' -J./work/build/moduleBuild/ -I./work/build/ -fintrinsic-modules-path /usr/local/galacticus/finclude -fintrinsic-modules-path /usr/local/galacticus/include -fintrinsic-modules-path /usr/local/galacticus/include/gfortran -fintrinsic-modules-path /usr/local/galacticus/lib/gfortran/modules -L/usr/local/galacticus/lib -L/usr/local/galacticus/lib64 -pthread -Wall -fbacktrace -ffpe-trap=invalid,zero,overflow -fdump-core -O3 -ffinite-math-only -fno-math-errno -fopenmp -g -DPROCPS -DOFDAVAIL -DFFTW3AVAIL -DANNUNAVAIL -DQHULLUNAVAIL -DMATHEVALUNAVAIL 2>&1 | ./scripts/build/postprocess.pl ./work/build/Galacticus.p.F90
./scripts/build/parameterDependencies.pl `pwd` Galacticus.exe
gfortran -c ./work/build/Galacticus.parameters.F90 -o ./work/build/Galacticus.parameters.o -ffree-line-length-none -frecursive -DBUILDPATH=\'./work/build\' -J./work/build/moduleBuild/ -I./work/build/ -fintrinsic-modules-path /usr/local/galacticus/finclude -fintrinsic-modules-path /usr/local/galacticus/include -fintrinsic-modules-path /usr/local/galacticus/include/gfortran -fintrinsic-modules-path /usr/local/galacticus/lib/gfortran/modules -L/usr/local/galacticus/lib -L/usr/local/galacticus/lib64 -pthread -Wall -fbacktrace -ffpe-trap=invalid,zero,overflow -fdump-core -O3 -ffinite-math-only -fno-math-errno -fopenmp -g -DPROCPS -DOFDAVAIL -DFFTW3AVAIL -DANNUNAVAIL -DQHULLUNAVAIL -DMATHEVALUNAVAIL
./scripts/build/sourceDigests.pl `pwd` Galacticus.exe
gcc -c ./work/build/Galacticus.md5s.c -o ./work/build/Galacticus.md5s.o -fopenmp -DBUILDPATH=\'./work/build\' -I./source/ -I./work/build/ -I/usr/local/galacticus/include -g -DOFDLOCKS -DPROCPS -DOFDAVAIL
gfortran `cat ./work/build/Galacticus.d` ./work/build/Galacticus.parameters.o ./work/build/Galacticus.md5s.o -o Galacticus.exe -ffree-line-length-none -frecursive -DBUILDPATH=\'./work/build\' -J./work/build/moduleBuild/ -I./work/build/ -fintrinsic-modules-path /usr/local/galacticus/finclude -fintrinsic-modules-path /usr/local/galacticus/include -fintrinsic-modules-path /usr/local/galacticus/include/gfortran -fintrinsic-modules-path /usr/local/galacticus/lib/gfortran/modules -L/usr/local/galacticus/lib -L/usr/local/galacticus/lib64 -pthread -Wall -fbacktrace -ffpe-trap=invalid,zero,overflow -fdump-core -O3 -ffinite-math-only -fno-math-errno -fopenmp -g -DPROCPS -DOFDAVAIL -DFFTW3AVAIL -DANNUNAVAIL -DQHULLUNAVAIL -DMATHEVALUNAVAIL `./scripts/build/libraryDependencies.pl Galacticus.exe -ffree-line-length-none -frecursive -DBUILDPATH=\'./work/build\' -J./work/build/moduleBuild/ -I./work/build/ -fintrinsic-modules-path /usr/local/galacticus/finclude -fintrinsic-modules-path /usr/local/galacticus/include -fintrinsic-modules-path /usr/local/galacticus/include/gfortran -fintrinsic-modules-path /usr/local/galacticus/lib/gfortran/modules -L/usr/local/galacticus/lib -L/usr/local/galacticus/lib64 -pthread -Wall -fbacktrace -ffpe-trap=invalid,zero,overflow -fdump-core -O3 -ffinite-math-only -fno-math-errno -fopenmp -g -DPROCPS -DOFDAVAIL -DFFTW3AVAIL -DANNUNAVAIL -DQHULLUNAVAIL -DMATHEVALUNAVAIL`
/usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
make: *** [work/build/Makefile_All_Execs:587: Galacticus.exe] Error 1
rm work/build/Galacticus.m

Could you help me resolve this? 

Thanks,
Axel

**Comment by grossa4747** [comment]
Hi Andrew, 
Thank you, everything compiles now, but I am getting an error while trying to run galacticus.exe
When I run (I think this is the replacement for quickParameters.xml, which does not exist in this branch):
./Galacticus.exe parameters/quicktest.xml 


I get:

Fatal error:
Unable to find data file "./static/darkMatter/Halo_Mass_Function_Parameters_Tinker_2008.xml"
 Occurred at:
     function:tinker2008ConstructorInternal
         file:structure_formation.halo_mass_function.Tinker2008.F90   [line 158]
  => Error occurred in master thread

I don't seem to have a static folder in the galacticus folder, so this is not surprising. 


I was following the instructions on the webpage here: https://github.com/galacticusorg/galacticus/wiki/Installation-from-source

I originally tried to use the installation script, but I was encountering a plethora of errors. It got to the point where I was basically installing each package manually because the script would fail for multiple different reasons, so I gave up on the script. 


Overall, I found the webpage decently easy to follow, but it took me several days to work through all the details of installation. Here are some notes on updates you could make to improve the installation experience:

1. The  gcc link is dead (I used gcc 10.1 instead). Additionally, you can compile gcc with multiple cores to save about 2 hours of compile time using make -j 8
2. Additionally, one needs to update the LD_LIBRARY_PATH. I succeeded by adding the following line to .bashrc
export LD_LIBRARY_PATH=LD_LIBRARY_PATH=$INSTALL_PATH/lib64:$INSTALL_PATH/lib:
$LD_LIBRARY_PATH
3. A warning about sudo changing the environment would be helpful. I had to use sudo to install hdf5 because of the location of my install path, but this doesn't take the environment variables and caused errors during installation, so you have to use something like sudo PATH="$PATH" HOME="$HOME" LD_LIBRARY_PATH="$LD_LIBRARY_PATH" make install to successfully install. This seems obvious in retrospect, but I am new to Linux and spent quite a while figuring this out. 
4. The BLAS instructions are confusing, and I wasn't sure if it mattered whether I used openBLAS or something else. I eventually used this version: https://netlib.org/blas/\
5. The quicktest setup seems to now be named quickTest.xml, not quickParameters.xml

**Comment by abensonca** [comment]
Thanks for this feedback - I'll make some changes to the installation guide to reflect these. The installation script is quite "brittle" - it works on a standard Ubuntu system, but it often fails on other systems - it's difficult to figure out compatibilities with all possible configurations.

Regarding the error you're getting, it sounds like Galacticus can't find the datasets that it needs at run time (I'll add a note about this to the installation guide also). You can do:
```
wget https://github.com/galacticusorg/datasets/archive/master.zip -O datasets.zip
unzip datasets.zip
```
to get the datasets. Then you'll need to set the `GALACTICUS_DATA_PATH` environment variable to the path to the `datasets` folder. Then when you run Galacticus it should be able to find them

Thanks again for the feedback, and if you run into any other problems, let me know.

**Comment by grossa4747** [comment]
Hi Andrew, 
Never mind, I realized that I needed to download the datasets and link them via GALACTICUS_DATA_PATH. Everything appears to be working now, thanks for the help.

**Comment by abensonca** [comment]
Happy to hear that it's working! I've updated the installation instructions. I'll close this issue now.
