### ISSUE TITLE
Makes the analysis code that finds self-bound particles in N-body simulations more robust

### ISSUE THREAD

**Issue by abensonca** [galacticusorg/galacticus#69]
**[Original report](https://bitbucket.org/galacticusdev/galacticus/issue/69) by Xiaolong Du (Bitbucket: [Xiaolong_Du](https://bitbucket.org/Xiaolong_Du), ).**

----------------------------------------

The current N-body analysis code to find self-bound particles is not very robust and has some bugs that leads to errors under certain circumstances.

- [X]  Segmentation fault. This only happens if multiple omp threads are used and appears randomly: several cases out of hundreds of runs. The error can be traced back to a threading issue in the function Add_Memory_Component() in utility.memory_management.F90 and can be fixed by adding an omp critical section including the main body of the function. More careful debugging is needed to figure out the exact reason that causes the problem.

- [X] Maximum iterations exceeded. In some cases, the analysis code can not find a convergent result. Increasing the number of maximum iterations does not seem to help. Outtputing the variable “weightBound” after each iteration may help find the reason. After some investigations, it is found that for some resampling data, the potential energy computed after several iterations become positive which results in marking all particles unbound. More analysis is needed to find out why this happens.

- [X] The mean position of self-bound particles found does not agree perfectly with the position of maximum density. This issue may have a consequence that the circular velocity competed by assuming the center of satellite at the mean position is not very accurate in some cases. One possible reason for this is that when computing the binding energy of particles we didn’t consider the tidal potential from the host halo, thus may have marked some unbound particles that are far from the satellite as bound particles. The plan is to check whether we can find an easy way to implement a tidal potential in the calculations and whether this will help to give more consistent results.

**Comment by abensonca** [comment]
@Xiaolong-Du are these issues still problems, or have they been resolved?

**Comment by Xiaolong-Du** [comment]
@abensonca The second issue is resolved.The third one is not a problem now as far as I understand

**Comment by Xiaolong-Du** [comment]
@abensonca The second issue is resolved. The third one is not a problem now as far I understand, because the position of maximum density should be a more reliable indicator of the satellite position. However, the first issue is still there I think. After the commit [4a70725](https://github.com/galacticusorg/galacticus/commit/4a70725354e91e9c864f8528909cd19a863f6768#diff-f2ae65eb6559278a1658d1d07c28e631), I do not get the segmentation fault errors any more. But I can not figure out why this commit may fix the issue. I can still reproduce the bug before the N-body analysis code is refactored into a task.

**Comment by Xiaolong-Du** [comment]
The first issue can be tracked back to the following line in the source file utility.memory_management.F90 (in the function Add_Memory_Component):

    write (temporaryString,formatString) trim(char(headerText)),join,trim(thisMemoryUsage%name)

The error happens randomly, e.g. one out of hundred of runs, and only appears when multiple threads are used. A similar issue I can find is a bug of internal writing in the gcc compiler. See below

    https://gcc.gnu.org/bugzilla/show_bug.cgi?id=78387

But I assume this is already fixed in the latest versions of gcc. Further investigations are still needed.

**Comment by abensonca** [comment]
That bug is fixed, but it could be related to this one https://gcc.gnu.org/bugzilla/show_bug.cgi?id=92836 which also involves the use of internal file units.

**Comment by abensonca** [comment]
It's not clear to me why 4a70725 affects issue number 1. But, it's a parallel thread race condition issue so any change could in principle affect how likely the issue is to be triggered.

**Comment by abensonca** [comment]
A possible workaround is to just wrap the problem line inside an OpenMP critical section:
```
!$omp critical(internalWrite)
write (temporaryString,formatString) trim(char(headerText)),join,trim(thisMemoryUsage%name)
!$omp end critical(internalWrite)
```

**Comment by Xiaolong-Du** [comment]
> A possible workaround is to just wrap the problem line inside an OpenMP critical section:
> 
> ```
> !$omp critical(internalWrite)
> write (temporaryString,formatString) trim(char(headerText)),join,trim(thisMemoryUsage%name)
> !$omp end critical(internalWrite)
> ```

Yes, adding critical sections can avoid issue 1. We probably need to include also the other lines containing internal writing in the critical section, i.e.

    !$omp critical(internalWrite)
    write (formatString,'(a,i1,a)') '(a,1x,a1,',spaceCount,'x,a)'
    write (temporaryString,formatString) trim(char(headerText)),join,trim(thisMemoryUsage%name)
    headerText=trim(temporaryString)
    write (usageString,'(1x,a1,1x,f7.3,a3)') join,dble(thisMemoryUsage%usage)/dble(thisMemoryUsage%divisor),thisMemoryUsage%suffix
    !$omp end critical(internalWrite)

**Comment by abensonca** [comment]
Agreed. Let's try adding that critical section. We should also add a "workaround" tag that refers to the GCC bugzilla issue. You can search for "`<workaround`" in the source code to find examples of this.

**Comment by Xiaolong-Du** [comment]
A workaround for issue 1 has been added to the orbitCalibration branch (see commit [f0b8419](https://github.com/galacticusorg/galacticus/commit/f0b8419701c64244bbafe8570b1ac8040045ea53)).

**Comment by abensonca** [comment]
Great! I'll go ahead and close this issue.
